const Story = () => {
  return (
    <section className="container pt-20">
      <div className="w-[216px] mb-[6px]">
        <span className="text-white text-[40px] font-black uppercase leading-10">
          a Story that started with
        </span>
        <span className="text-rose-500 text-[40px] font-black uppercase leading-10">
          {" "}
          one simple
          <br />
          ape
        </span>
      </div>
      <p className="w-[216px] mb-9 text-right text-white text-base font-normal font-messinaSans uppercase leading-[19px]">
        WHO GOT
        <br />
        FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW THE IDEA OF
        ESCAPING AND DYNAMIC JOURNEY ON THE YACHT
      </p>
      <div className="w-[216px] h-24 flex-col justify-start items-center gap-4 inline-flex">
        <svg className="w-[18px] h-[18px] stroke-[#FFFFFF]">
          <use xlinkHref="/sprite/sprite.svg#icon-cross"></use>
        </svg>
        <div className="w-[216px] text-center text-white text-xs font-normal font-['Messina Sans Mono'] uppercase leading-[14px]">
          EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS ARE
          RANDOMLY GENERATED BY USERS
        </div>
      </div>
    </section>
  );
};

export default Story;
