import type { Metadata } from "next";
import "./globals.css";
import {
  biroScript,
  biroScriptUS,
  messinaSans,
  rightGrotesk,
} from "@/utils/custom-fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${messinaSans.variable} ${biroScript.variable} ${biroScriptUS.variable} ${rightGrotesk.className}`}
      >
        {children}
      </body>
    </html>
  );
}
